### ISSUE TITLE
Bug Report | 追加委托后原先产生的收益被清空

### ISSUE THREAD

**Issue by BlankerL** [gatechain/gatechain-docs#2]
### 问题描述
对某个节点委托并产生收益后，再次增加对该节点的委托token数量，会导致原先积累的收益被清空。

### 复现方法
对某个节点进行委托（比如委托900GT），产生一定收益（比如0.1GT）后再追加一部分GT进行委托（比如100GT），此时原先产生的0.1GT被清空重新计算，而并不会将收益提现。

追加委托的转账ID：
`BASIC-671C0EDBE01216CFEF4932061DD6F7F50274600D4451BD7A8F45271FE91569990AC48FFC4DA789FB86B7F472FC43DDC7`
提取奖励的转账ID：
`BASIC-35365B96F0DDCD3C2AF1FBED70C2F2274C338D06B3367F36E97F93EA1DCAA3A0F187BC5355CE3462C51ED68D90304EDC`

### 问题
经过多次测试均可以复现这个问题，这个bug在我看来比较严重，我想确认一下，被清空重新计算的GT最终的归属是谁？如何保证GateChain的通胀是稳定的？

**Comment by vincentbdb** [comment]
针对节点进行增加委托、转移委托、解除委托的时候，都会触发收益的自动结算。交易发起时，以前的收益并没有清空，而是结算到账户的余额了。
可以通过API查询“追加委托的转账”详情：http://api.testnet.gatenode.cc:1317/v1/tx/671C0EDBE01216CFEF4932061DD6F7F50274600D4451BD7A8F45271FE91569990AC48FFC4DA789FB86B7F472FC43DDC7
log中的transfer信息显示了收益归属：
{
                    "attributes":[
                        {
                            "key":"recipient",
                            "value":"gt1148gzp5mgnq74mzg2mwfnvrw6eefmxw7cev27ncyj9m87d7l5xmsps3sd9freu3vcmcd7p7"
                        },
                        {
                            "key":"amount",
                            "value":"1177578NANOGT"
                        }
                    ],
                    "type":"transfer"
                }

**Comment by BlankerL** [comment]
> 针对节点进行增加委托、转移委托、解除委托的时候，都会触发收益的自动结算。交易发起时，以前的收益并没有清空，而是结算到账户的余额了。
> 可以通过API查询“追加委托的转账”详情：http://api.testnet.gatenode.cc:1317/v1/tx/671C0EDBE01216CFEF4932061DD6F7F50274600D4451BD7A8F45271FE91569990AC48FFC4DA789FB86B7F472FC43DDC7
> log中的transfer信息显示了收益归属：
> {
> "attributes":[
> {
> "key":"recipient",
> "value":"gt1148gzp5mgnq74mzg2mwfnvrw6eefmxw7cev27ncyj9m87d7l5xmsps3sd9freu3vcmcd7p7"
> },
> {
> "key":"amount",
> "value":"1177578NANOGT"
> }
> ],
> "type":"transfer"
> }

非常感谢，没有注意到委托和结算发生在同一笔订单当中。
